name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    name: Run unit tests (FAST_TRAIN)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc g++ | cat

      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Create necessary directories
        run: mkdir -p models data

      - name: Run basic import tests
        run: python -c "import src.features; import src.model; import src.data; print('imports ok')"

      - name: Run tests
        env:
          FAST_TRAIN: "1"
        run: python -m pytest tests/ -q --timeout=300

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: ${{ secrets.GHCR_TOKEN != '' && secrets.GHCR_USERNAME != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build (and optionally push) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ secrets.GHCR_TOKEN != '' && secrets.GHCR_USERNAME != '' }}
          tags: ghcr.io/${{ github.repository_owner }}/house-price-app:${{ github.sha }}
